### ISSUE TITLE
pip instalation is failing on windows

### ISSUE THREAD

**Issue by railbox** [Salamek/picpro#9]
```Collecting picpro
  Using cached picpro-0.1.2.tar.gz (37 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pyserial in c:\python310\lib\site-packages (from picpro) (3.5)
Requirement already satisfied: docopt in c:\python310\lib\site-packages (from picpro) (0.6.2)
Collecting intelhex (from picpro)
  Using cached intelhex-2.3.0-py2.py3-none-any.whl.metadata (2.7 kB)
Using cached intelhex-2.3.0-py2.py3-none-any.whl (50 kB)
Building wheels for collected packages: picpro
  Building wheel for picpro (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\picpro
      copying picpro\ChipInfoEntry.py -> build\lib\picpro
      copying picpro\ChipInfoReader.py -> build\lib\picpro
      copying picpro\exceptions.py -> build\lib\picpro
      copying picpro\HexFileReader.py -> build\lib\picpro
      copying picpro\IChipInfoEntry.py -> build\lib\picpro
      copying picpro\ProgrammingVars.py -> build\lib\picpro
      copying picpro\ProtocolInterface.py -> build\lib\picpro
      copying picpro\tools.py -> build\lib\picpro
      copying picpro\__init__.py -> build\lib\picpro
      copying picpro\__main__.py -> build\lib\picpro
      creating build\lib\picpro\bin
      copying picpro\bin\picpro.py -> build\lib\picpro\bin
      copying picpro\bin\__init__.py -> build\lib\picpro\bin
      installing to build\bdist.win-amd64\wheel
      running install
      running install_lib
      creating build\bdist.win-amd64
      creating build\bdist.win-amd64\wheel
      creating build\bdist.win-amd64\wheel\picpro
      creating build\bdist.win-amd64\wheel\picpro\bin
      copying build\lib\picpro\bin\picpro.py -> build\bdist.win-amd64\wheel\.\picpro\bin
      copying build\lib\picpro\bin\__init__.py -> build\bdist.win-amd64\wheel\.\picpro\bin
      copying build\lib\picpro\ChipInfoEntry.py -> build\bdist.win-amd64\wheel\.\picpro
      copying build\lib\picpro\ChipInfoReader.py -> build\bdist.win-amd64\wheel\.\picpro
      copying build\lib\picpro\exceptions.py -> build\bdist.win-amd64\wheel\.\picpro
      copying build\lib\picpro\HexFileReader.py -> build\bdist.win-amd64\wheel\.\picpro
      copying build\lib\picpro\IChipInfoEntry.py -> build\bdist.win-amd64\wheel\.\picpro
      copying build\lib\picpro\ProgrammingVars.py -> build\bdist.win-amd64\wheel\.\picpro
      copying build\lib\picpro\ProtocolInterface.py -> build\bdist.win-amd64\wheel\.\picpro
      copying build\lib\picpro\tools.py -> build\bdist.win-amd64\wheel\.\picpro
      copying build\lib\picpro\__init__.py -> build\bdist.win-amd64\wheel\.\picpro
      copying build\lib\picpro\__main__.py -> build\bdist.win-amd64\wheel\.\picpro
      running install_data
      creating build\bdist.win-amd64\wheel\picpro-0.1.2.data
      creating build\bdist.win-amd64\wheel\picpro-0.1.2.data\data
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Toxa\AppData\Local\Temp\pip-install-7u_nr1db\picpro_18acd05709e84dbca8816aaa57826c6f\setup.py", line 12, in <module>
          setup(
        File "C:\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Python310\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Python310\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Python310\lib\site-packages\wheel\bdist_wheel.py", line 399, in run
          self.run_command("install")
        File "C:\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Python310\lib\site-packages\setuptools\command\install.py", line 61, in run
          return orig.install.run(self)
        File "C:\Python310\lib\distutils\command\install.py", line 580, in run
          self.run_command(cmd_name)
        File "C:\Python310\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Python310\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Python310\lib\distutils\command\install_data.py", line 56, in run
          dir = convert_path(f[0])
        File "C:\Python310\lib\distutils\util.py", line 124, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/usr/share\picpro' cannot be absolute
      [end of output]

**Comment by Salamek** [comment]
Hmm this was never meant/created to run under windows BUT i have made changes to allow that, this^ should be fixed in 0.1.3
